project:
  type: book
  output-dir: docs
  preview:
    port: 9001
    browser: true

book:
  title: "Fundamentos de Ingeniería de Datos"
  subtitle: "Un enfoque práctico"
  author: "Felipe Ortega"
  date: "2024-07-17"
  chapters:
    - index.qmd
    - part: "Fundamentos de ingeniería de datos"
      chapters:
        - 01-apps.qmd
        - 02-pipelines.qmd
    - part: "Entornos de procesamiento distribuido de datos"
      chapters:
        - 03-tech-dist.qmd
        - 04-hybrid-envs.qmd
    - part: "Desarrollo de aplicaciones de procesamiento de datos"
      chapters:
        - 05-struct-data.qmd
        - 06-semi-unstruct-data.qmd
    - part: "Aprendizaje máquina escalable"
      chapters:
        - 07-scalable-ml.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf]
  repo-url: https://github.com/glimmerphoenix/dataeng_book
  repo-actions: [source, edit, issue]
lang: es
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrbook
    classoption:
      - a4paper 
      - oneside
      - parskip=half+
      - numbers=noenddot
      - cleardoublepage=empty
      - DIV=15
    hyperrefoptions: 
      - linktocpage=true
    include-in-header: 
       text: |
        % Line and page breaking
        \sloppy
        \clubpenalty = 10000
        \widowpenalty = 10000
        \brokenpenalty = 10000

        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }



