project:
  type: book
  output-dir: docs

book:
  title: "Fundamentos de Ingeniería de Datos"
  subtitle: "Un enfoque práctico"
  author: "Felipe Ortega"
  date: "2024-07-17"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
lang: es
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



